disabled_rules:  # rule identifiers to exclude from running
#  - colon
#  - comma
#  - control_statement
#  - cyclomatic_complexity
#  - trailing_comma
#  - trailing_whitespace
  - identifier_name
#  - file_length
#  - large_tuple
#  - force_cast
#  - force_try
  - type_body_length
  - function_parameter_count
opt_in_rules: # some rules are only opt-in
  - closing_brace
  - opening_brace
  - return_arrow_whitespace
  - trailing_semicolon
  - statement_position
line_length:
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Playground
  - Frameworks/
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
reporter: "xcode"
