workspace 'GeoTracker.xcworkspace'
platform :ios, '10.0'
inhibit_all_warnings!
use_frameworks!

def shared_pods
  pod 'CoreGPX'
end

target 'GeoTracker' do
  project 'GeoTracker.xcodeproj'
  shared_pods

	target 'GeoTrackerUITests' do
			inherit! :search_paths
	end
end

target 'GeoTrackerCore' do
  project 'GeoTrackerCore/GeoTrackerCore.xcodeproj'
  shared_pods
end
