# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

workspace 'GeoTracker.xcworkspace'

def shared_pods
  pod 'CoreGPX'
end

target 'getlocation' do
  use_frameworks!
  project 'getlocation.xcodeproj'
  shared_pods

end

target 'GeoTrackerCore' do
  use_frameworks!
  project 'GeoTrackerCore/GeoTrackerCore.xcodeproj'
  shared_pods
end
